- src/app/routes/applications/new-application/new-application.component.html
- src/app/routes/applications/new-application/new-application.component.ts
- src/app/routes/applications/new-organization/new-organization.component.html
- src/app/routes/applications/new-organization/new-organization.component.ts
- src/app/routes/applications/new-role/new-role.component.html
- src/app/routes/applications/new-role/new-role.component.ts
- src/app/routes/applications/transfer-ownership/transfer-ownership.component.html
- src/app/routes/applications/transfer-ownership/transfer-ownership.component.ts
- src/app/shared/services/iam.service.ts
Input Validations for:
DID
Eth Address
Others
> [MYEN-479] Add input validations

- src/app/routes/applications/governance-list/governance-list.component.html
- src/app/routes/applications/governance-list/governance-list.component.ts
Added filter for role on Role Governance tab. Essentially a copy-paste of the other filters.
Adjusted filter column size to fit role filter
> Role filter on role governance

- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/search-result/search-result.component.ts
- src/app/shared/services/loading.service.ts
Revert code in show loading to remove timeout and transfer it to dashboard upon redirecting to other page
> MYEN-536 Fix infinite loading screen in search result

- src/app/routes/applications/applications.component.ts
- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.ts
- src/app/routes/enrolment/enrolment.component.ts
- src/app/routes/search-result/search-result.component.ts
- src/app/shared/services/loading.service.ts
- src/app/shared/services/url-param.service.spec.ts
- src/app/shared/services/url-param.service.ts
Preserve selected tab upon refresh
> MYEN-538 Preserve selected tab

- package-lock.json
- src/app/layout/header/header.component.ts
- src/app/routes/applications/governance-list/governance-list.component.html
- src/app/routes/applications/governance-list/governance-list.component.ts
- src/app/routes/applications/transfer-ownership/transfer-ownership.component.html
- src/app/routes/applications/transfer-ownership/transfer-ownership.component.ts
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.html
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.ts
- src/app/routes/enrolment/enrolment.component.html
- src/app/routes/enrolment/enrolment.component.ts
- src/app/routes/enrolment/view-requests/view-requests.component.html
- src/app/routes/enrolment/view-requests/view-requests.component.ts
- src/environments/environment.ts
Fix issue on cannot transfer ownership
> [MYEN-542] Cannot transfer ownership

- package-lock.json
- src/app/layout/header/header.component.ts
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.html
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.ts
- src/app/routes/enrolment/enrolment.component.html
- src/app/routes/enrolment/enrolment.component.ts
- src/app/routes/enrolment/view-requests/view-requests.component.html
- src/app/routes/enrolment/view-requests/view-requests.component.ts
- Cancel Claim Request
- Add **Rejected** option in dropdown for proper filter
- Updated message listener & notifications counter
> [MYEN-512] Cancel Claim Request

- src/app/routes/registration/request-claim/request-claim.component.html
Change label of the button from "Register" to "Submit Request" within enrolment page
> Modified button label

- src/environments/environment.ts
https://identitycache-dev.energyweb.org/ - **cache server**
https://identityevents-dev.energyweb.org/ - **nats exchange**
> Update Dev URLs

- src/app/routes/applications/governance-view/governance-details/governance-details.component.html
- src/app/routes/applications/governance-view/governance-details/governance-details.component.ts
- src/app/routes/registration/connect-to-wallet-dialog/connect-to-wallet-dialog.component.html
- src/app/routes/registration/request-claim/request-claim.component.ts
Redirect enrolment in same screen & login first before using iam-client-lib functions in enrolment screen
> [MYEN-618] Redirect Enrolment on the same screen

- src/app/layout/header/header.component.ts
Handle Duplicate Messages from NATS Server to avoid incorrect notif counts
> [MYEN-623] Handle Duplicate Messages from NATS 

- src/app/shared/services/iam.service.ts
Only KM has 2 minute timeout. Other providers still have 1 minute
> MYEN635 Increase timeout for KM signin to 2 minutes

- package-lock.json
- package.json
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.html
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.ts
Waiting for Daniel to update iam-client-lib version before I send this PR for review.
> [MYEN-555] Cancel Claim Request

- package-lock.json
- package.json
- src/app/routes/applications/applications.component.html
- src/app/routes/applications/applications.component.ts
- src/app/routes/applications/governance-list/governance-list.component.html
- src/app/routes/applications/governance-list/governance-list.component.ts
- src/app/routes/applications/new-organization/new-organization.component.html
- src/app/routes/applications/new-organization/new-organization.component.ts
- src/app/shared/services/iam.service.ts
This PR still has below 2 issues:
- Update sub-org details doesn't reflect after successful save
- Org List does not contain transferred sub-orgs if excludeSubOrgs is true (otherwise, the list will display all orgs by the user regardless if parent or sub-org)
> [MYEN-651] Implement Sub-Org

- src/app/routes/applications/governance-view/governance-details/governance-details.component.html
- src/app/routes/applications/governance-view/governance-details/governance-details.component.ts
- src/app/routes/applications/new-role/new-role.component.html
- src/app/routes/applications/new-role/new-role.component.ts
- src/app/routes/registration/request-claim/request-claim.component.html
- src/app/routes/registration/request-claim/request-claim.component.ts
- Added **Set Restrictions** section in Create/Update Role
- Implemented restriction in Enrolment screen
> Restrict enrolment

- package-lock.json
- package.json
- src/app/layout/header/header.component.html
- src/app/routes/applications/applications.component.html
- src/app/routes/applications/applications.module.ts
- src/app/routes/applications/new-application/new-application.component.html
- src/app/routes/applications/new-asset-type/new-asset-type.component.html
- src/app/routes/applications/new-asset-type/new-asset-type.component.scss
- src/app/routes/applications/new-asset-type/new-asset-type.component.spec.ts
- src/app/routes/applications/new-asset-type/new-asset-type.component.ts
- src/app/routes/applications/new-passive-asset/new-passive-asset.component.html
- src/app/routes/applications/new-passive-asset/new-passive-asset.component.spec.ts
- src/app/routes/applications/new-passive-asset/new-passive-asset.component.ts
- src/app/routes/assets/assets.component.html
- src/app/routes/assets/assets.component.spec.ts
- src/app/routes/assets/assets.component.ts
- src/app/routes/assets/assets.module.ts
- src/app/routes/dashboard/dashboard.component.html
- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/routes.module.ts
- src/app/routes/routes.ts
- src/app/shared/styles/app/material/button.scss
- src/app/shared/styles/app/material/md-inputs.scss
> Added asset management skeleton

- src/app/routes/assets/assets.component.html
- src/app/routes/assets/assets.component.ts
Edit icon beside asset name
Added asset image/logo
> Added edit icon and asset image

- src/app/routes/applications/governance-view/governance-details/governance-details.component.ts
- src/app/routes/applications/new-application/new-application.component.ts
- src/app/routes/applications/new-organization/new-organization.component.ts
- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/registration/request-claim/request-claim.component.ts
Affected Screens:
- View Org/App Details
- Update Org/App Details
- Enrol to Role
> [MYEN-781] Fix issue on JSON (Others)

- package-lock.json
- package.json
- src/app/layout/header/header.component.ts
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.ts
Refresh enrolment lists depending on events received from iam-client-lib
Unsubscribe to iam-client-lib subscriptions upon component destroy
> [SWTCH-863] Refresh enrolment lists upon receipt of events

- package-lock.json
- package.json
> feat: update iam-client-lib to 3.0.0-alpha.9

- src/app/routes/assets/asset-ownership-history/asset-ownership-history.component.html
- src/app/routes/assets/asset-ownership-history/history-element/history-element.component.html
- src/app/routes/assets/asset-ownership-history/history-element/history-element.component.spec.ts
- src/app/routes/assets/asset-ownership-history/history-element/history-element.component.ts
- src/app/routes/assets/asset-ownership-history/history-period/history-period.component.html
- src/app/routes/assets/asset-ownership-history/history-period/history-period.component.scss
- src/app/routes/assets/asset-ownership-history/history-period/history-period.component.spec.ts
- src/app/routes/assets/asset-ownership-history/history-period/history-period.component.ts
- src/app/routes/assets/assets.module.ts
If this is ASSET_TRANSFERRED we should display offered from/owner labels.
> SWTCH-891 change labels owner/offer to depending on event type.

- angular.json
- src/app/routes/assets/asset-enrolment-list/asset-enrolment-list.component.html
- src/app/routes/assets/asset-enrolment-list/asset-enrolment-list.component.ts
- src/app/routes/enrolment/enrolment-list/enrolment-list.component.ts
- src/app/routes/enrolment/enrolment.component.html
- src/app/routes/enrolment/enrolment.component.ts
This PR is created by the request of Vadym.
> [SWTCH-299] Add filter enrollment requests

- package-lock.json
- package.json
- src/app/routes/applications/new-role/new-role.component.ts
Minor changes need to create and update Roles, Apps, Orgs using the new RoleDefinitionResolver smart contract:
- feat(new-role.component): use number version. As number was previously strings of the format "1.0.0", need to convert into a number as we are now using integers for role versions
Still in DRAFT as need to integrate updated iam-client-lib first
> SWTCH-968 Integrate new org/app/role definition creation into SB

- src/app/routes/applications/governance-list/governance-list.component.html
- src/app/routes/applications/governance-list/governance-list.component.scss
Add disable style to action menu item.
> [SWTCH-989] Add disable menu item

- src/app/layout/header/header.component.html
- src/app/routes/assets/asset-list/asset-list.component.html
- src/app/routes/search-result/search-result.component.html
- src/app/shared/styles/app/layout.scss
- src/app/shared/styles/app/material/table.scss
- src/app/shared/styles/themes/theme-b.scss
fix header menu highlight (active) and some minor styling issue
> [SWTCH-987] Menu highlight

- src/app/routes/registration/enrolment-form/enrolment-form.component.html
- src/app/routes/registration/enrolment-form/enrolment-form.component.spec.ts
- src/app/routes/registration/enrolment-form/enrolment-form.component.ts
- src/app/routes/registration/registration.module.ts
- src/app/routes/registration/request-claim/request-claim.component.html
- src/app/routes/registration/request-claim/request-claim.component.ts
Update info after refactoring and adding tests to enrolmentForm.
1. Removed few not needed properties from `request-claim.component.ts`
2. Extracted to new component entire form for enrolment.
3. Added additional error messages to: datepicker, registration types checkboxes (on/off chain).
4. Added tests for: on/off chain and submit button, displayed error messages (if they appear and have correct message). I think it is useful because we are generating there those fields so it's better to check if everything is fine.
If there are any proposition to test something more or to change some description, feel free to comment :)
> SWTCH-1049 submit button disabled with valid form

- src/app/layout/header/header.component.html
- src/app/routes/dashboard/card/card.component.html
- src/app/routes/dashboard/card/card.component.spec.ts
- src/app/routes/dashboard/card/card.component.ts
- src/app/routes/dashboard/dashboard.component.html
- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/dashboard/dashboard.module.ts
- src/app/routes/routes.ts
- src/app/routes/stake/providers/providers.component.html
- src/app/routes/stake/providers/providers.component.spec.ts
- src/app/routes/stake/providers/providers.component.ts
- src/app/routes/stake/stake-routing.module.ts
- src/app/routes/stake/stake.component.html
- src/app/routes/stake/stake.component.spec.ts
- src/app/routes/stake/stake.component.ts
- src/app/routes/stake/stake.module.ts
Creating module and basic routing with component for staking functionality.
I moved also dashboard cards into component, so it will be easier to change/maintain this part of code.
> SWTCH-1045 prepare sb for staking functionality

- src/app/app.module.ts
- src/app/layout/header/header.component.html
- src/app/routes/dashboard/dashboard.component.html
- src/app/routes/routes.ts
- src/app/shared/feature-toggle/feature-toggle.directive.spec.ts
- src/app/shared/feature-toggle/feature-toggle.directive.ts
- src/app/shared/feature-toggle/feature-toggle.guard.spec.ts
- src/app/shared/feature-toggle/feature-toggle.guard.ts
- src/app/shared/feature-toggle/feature-toggle.interface.ts
- src/app/shared/feature-toggle/feature-toggle.token.ts
- src/app/shared/shared.module.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
I created a directive that works like ngIf, but looks on property featureVisible in environment.
There is also a guard that blocks navigating to specific route. So there will be no possibility to navigate to a disabled feature, because it will be blocked.
I did it generic at this moment.
> SWTCH-1046 feature flag for staking functionality

- src/app/layout/header/dialog-user/dialog-user.component.html
- src/app/layout/header/dialog-user/dialog-user.component.spec.ts
- src/app/layout/header/dialog-user/dialog-user.component.ts
There was no error messages, only highlighted fields. So i added them, I wrote few unit tests and refactored a little bit.
> SWTCH-1101 missing error messages

- package-lock.json
- package.json
This version uses the new Claim and IdentityManager smart contracts
This allows on-chain roles to be submit for assets by owners
> chore: update iam-client-lib to 3.0.0-alpha.28

- src/app/routes/applications/governance-list/governance-list.component.ts
- src/app/routes/applications/new-staking-pool/new-staking-pool.component.html
- src/app/routes/applications/new-staking-pool/new-staking-pool.component.scss
- src/app/routes/applications/new-staking-pool/new-staking-pool.component.spec.ts
- src/app/routes/applications/new-staking-pool/new-staking-pool.component.ts
- src/app/routes/applications/new-staking-pool/staking-pool.service.spec.ts
- src/app/routes/applications/new-staking-pool/staking-pool.service.ts
- src/app/shared/services/iam.service.ts
- src/app/state/stake/stake.actions.ts
- src/app/state/stake/stake.effects.ts
Implementation of staking pool creation. To test it you have to link branch https://github.com/energywebfoundation/iam-client-lib/pull/204 locally in switchboard and have at least 100 volta tokens on your account (i don't have such amount).
> SWTCH-1064 create staking pool implementation

- src/app/routes/applications/governance-list/governance-list.component.ts
- src/app/routes/routes.module.ts
- src/app/shared/services/iam.service.ts
In this PR I'm removing `#` from url. There was less work than i thought.
> SWTCH-1121 remove hash from url

- src/app/routes/assets/verification-method/verification-method.component.ts
- src/app/utils/validators/list-contains.validator.ts
- src/app/utils/validators/validators.spec.ts
I deleted the old branch and created this new one as trying to merge made changes to 89 files. Also removed the previous toastr error implementation and used a form error.
> finished chore of multiple key validation

- src/app/routes/applications/new-role/components/role-field/role-field.component.html
- src/app/routes/applications/new-role/components/role-field/role-field.component.scss
> Fixed Issue with year on the role restrictions step

- src/app/routes/ewt-patron/ewt-patron.module.ts
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.html
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.scss
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.ts
- src/app/routes/ewt-patron/staking-footer/staking-footer.component.html
- src/app/routes/ewt-patron/staking-footer/staking-footer.component.scss
- src/app/routes/ewt-patron/staking-footer/staking-footer.component.spec.ts
- src/app/routes/ewt-patron/staking-footer/staking-footer.component.ts
- src/app/routes/ewt-patron/staking-header/staking-header.component.html
- src/app/routes/ewt-patron/staking-header/staking-header.component.scss
- src/app/routes/ewt-patron/staking-header/staking-header.component.spec.ts
- src/app/routes/ewt-patron/staking-header/staking-header.component.ts
- src/app/shared/services/iam.service.ts
- src/app/shared/services/staking/staking.service.spec.ts
- src/app/shared/services/staking/staking.service.ts
- src/app/state/auth/auth.effects.spec.ts
- src/app/state/auth/auth.effects.ts
- src/app/state/stake/stake.actions.ts
- src/app/state/stake/stake.effects.spec.ts
- src/app/state/stake/stake.effects.ts
- src/app/state/stake/stake.selectors.spec.ts
- src/app/state/stake/stake.selectors.ts
Adding tests, clean up, splitting into more components etc.
> SWTCH-1143 update staking page

- .github/workflows/deploy.yml
Added linter script and deploy for `staging` branch.
> extend gh actions

- src/app/layout/header/dialog-user/dialog-user.component.spec.ts
This test was failing on Sundays... I used wrong method.
> use getDate instead of getDay to create a date string in test.

- src/app/routes/applications/actions/action-base.abstract.ts
- src/app/routes/applications/actions/action-test.utils.ts
- src/app/routes/applications/actions/application-actions/application-actions.component.html
- src/app/routes/applications/actions/application-actions/application-actions.component.spec.ts
- src/app/routes/applications/actions/application-actions/application-actions.component.ts
- src/app/routes/applications/actions/organization-actions/organization-actions.component.html
- src/app/routes/applications/actions/organization-actions/organization-actions.component.spec.ts
- src/app/routes/applications/actions/organization-actions/organization-actions.component.ts
- src/app/routes/applications/actions/role-actions/role-actions.component.html
- src/app/routes/applications/actions/role-actions/role-actions.component.spec.ts
- src/app/routes/applications/actions/role-actions/role-actions.component.ts
- src/app/routes/applications/applications.module.ts
- src/app/routes/applications/governance-list/governance-list.component.html
- src/app/routes/applications/governance-list/governance-list.component.ts
1. Checks if organization is a provider - if not shows action to create staking pool.
2. Move actions to separate components for org/apps/roles.
3. Show copy to clipboard staking url only when organization is provider. 
4. Removes double checking if an organization/role/app belongs to the current user.
> SWTCH-1142 implement button to copy staking url

- src/app/layout/header/dialog-user/dialog-user.component.spec.ts
Fixing failing tests because of creating wrong format of date in spec file.
> fix: setting date in dialog user tests.

- package-lock.json
- package.json
- src/app/layout/header/header.component.ts
- src/app/layout/layout.component.ts
- src/app/modules/connect-to-wallet/connect-to-wallet-dialog/connect-to-wallet-dialog.component.spec.ts
- src/app/modules/connect-to-wallet/connect-to-wallet-dialog/connect-to-wallet-dialog.component.ts
- src/app/routes/applications/governance-list/governance-list.component.ts
- src/app/routes/applications/new-application/new-application.component.ts
- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.spec.ts
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.ts
- src/app/routes/registration/request-claim/request-claim.component.ts
- src/app/routes/welcome/welcome.component.html
- src/app/routes/welcome/welcome.component.ts
- src/app/shared/services/iam-listener/iam-listener.service.spec.ts
- src/app/shared/services/iam-listener/iam-listener.service.ts
- src/app/shared/services/iam.service.ts
- src/app/shared/services/login/login.service.spec.ts
- src/app/shared/services/login/login.service.ts
- src/app/state/auth/auth.actions.ts
- src/app/state/auth/auth.effects.spec.ts
- src/app/state/auth/auth.effects.ts
- src/app/state/auth/auth.reducer.ts
- src/app/state/user-claim/user.actions.ts
- src/app/state/user-claim/user.effects.ts
Rewriting and unifying authorization. Few parts are divided + few tests. Solves few problems from user perspective.
> SWTCH-1164 improve login functionality

- src/app/routes/assets/asset-list/asset-list.component.ts
Error occurs when we do not have assets at all and we go to assets offered to me.
> SWTCH-1191 fix: error when getting claims by empty list of subjects.

- karma-headless.conf.js
- src/app/routes/assets/verification-method/verification-method.component.ts
- src/app/routes/ewt-patron/stake-success/stake-success.component.spec.ts
- src/app/routes/registration/enrolment-form/enrolment-form.component.spec.ts
- src/app/routes/stake/details/description/description.component.spec.ts
- src/app/routes/stake/details/terms/terms.component.spec.ts
- src/app/routes/stake/enrolment/enrolment.component.spec.ts
- src/app/routes/stake/enrolment/final-review/final-review.component.spec.ts
Removes errors from tests about for example not found selector etc.
> SWTCH-1193 remove setup errors from unit tests

- src/app/shared/services/iam-listener/iam-listener.service.ts
- src/app/shared/services/login/helpers/swal-login-error-handler.ts
- src/app/shared/services/login/login.service.ts
This one is not easy to test in switchboard, because it depends on token expiration.
> SWTCH-1188 not reloading page when gets 500 status code error

- src/app/routes/assets/asset-list/asset-list.component.ts
- src/app/routes/assets/assets.component.ts
List wasn't refreshed when there is only one offered asset and is rejected.
> SWTCH-1204 fix refreshing list after rejecting last asset.

- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.spec.ts
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.ts
- src/app/routes/registration/request-claim/request-claim.component.ts
- src/app/state/auth/auth.actions.ts
- src/app/state/auth/auth.effects.spec.ts
- src/app/state/auth/auth.effects.ts
- src/app/state/index.ts
- src/app/state/layout/layout-store-slice.module.ts
- src/app/state/layout/layout.actions.ts
- src/app/state/layout/layout.effects.spec.ts
- src/app/state/layout/layout.effects.ts
- src/app/state/layout/layout.reducer.spec.ts
- src/app/state/layout/layout.reducer.ts
- src/app/state/layout/layout.selectors.spec.ts
- src/app/state/layout/layout.selectors.ts
- src/app/state/stake/stake.effects.spec.ts
- src/app/state/stake/stake.effects.ts
- src/app/state/store-root.module.ts
The error occurs when you have some organizations and tries to go directly to [switchboard-dev.energyweb.org/governance](switchboard-dev.energyweb.org/governance) page. There is a race condition, which will be first: initialization of staking pool or getting list of organizations which cause an error. This PR solves problem by redirecting to governance page after successful staking pool initialization.
> fix(auth): SWTCH-1205 race condition when initializing staking pool.

- src/app/shared/pipes/did-format-minifier.pipe.spec.ts
- src/app/shared/pipes/did-format-minifier.pipe.ts
Adds tests for did format minifier pipe + small refactoring.
> refactor did format minifier. add tests to it.

- src/app/routes/applications/applications.module.ts
- src/app/routes/applications/new-role/components/fields-summary/fields-summary.component.html
- src/app/routes/applications/new-role/components/fields-summary/fields-summary.component.spec.ts
- src/app/routes/applications/new-role/components/fields-summary/fields-summary.component.ts
- src/app/routes/applications/new-role/components/role-field/role-field.component.html
- src/app/routes/applications/new-role/components/role-field/role-field.component.spec.ts
- src/app/routes/applications/new-role/new-role.component.html
Updates role creation fields summary (confirm details step) with new design. Reuses the same component in two places.
> SWTCH-1207 connect role summary design with data

- package-lock.json
- package.json
ICL-105
Fix is standardization of publicKey format
> fix: update iam-client-lib to fix "incorrect-sig"

- src/app/routes/applications/new-role/new-role.component.ts
- src/app/shared/services/iam.service.ts
- src/app/utils/validators/is-hex/is-hex.validator.spec.ts
- src/app/utils/validators/is-hex/is-hex.validator.ts
Adding tests + small refactoring. I checked it also in application if it is working.
> chg(validators): refactor isDidValid validator and move it to other validators.

- package-lock.json
- package.json
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.html
- src/app/routes/ewt-patron/stake-success/stake-success.component.html
- src/app/routes/ewt-patron/stake/stake.component.html
- src/app/routes/ewt-patron/stake/stake.component.ts
- src/app/shared/services/iam.service.ts
- src/app/shared/services/pool/staking-pool-facade.ts
- src/app/shared/services/staking/staking-pool-service-facade.ts
- src/app/state/pool/models/const.ts
- src/app/state/pool/pool.actions.ts
- src/app/state/pool/pool.effects.spec.ts
- src/app/state/pool/pool.effects.ts
- src/app/state/pool/pool.reducer.ts
- src/app/state/pool/pool.selectors.spec.ts
- src/app/state/pool/pool.selectors.ts
- src/env.js
This PR provides few changes:
- limit to 50,000 EWT per DID - this information is from iam-client-lib
- validation of stake value - do not allow to put stake above maximum value
- allow to stake multiple times
- information about taken gas price for transaction
> SWTCH-1234 dsla tasks

- package-lock.json
- package.json
- src/app/layout/header/header.component.ts
new nats subject format  {event-type}.{topic}.{did}.{environment} with hidden sensitive info in body
> feat(nats): new nats event format

- package-lock.json
- package.json
> feat: update iam client lib to version 4.0.0-alpha.3

- scripts/prod-env.js
- src/app/shared/services/env/env.service.ts
- src/app/shared/services/iam.service.ts
- src/env.js
NATS_ENVIRONMENT_NAME is required for correct nats events namespace subscribtion
> feat(nats): nats env name

- package-lock.json
- package.json
This should fix the authentication issues + fix dto validation failure in cache-server
> chore: update ICL to alpha.6

- package-lock.json
- package.json
latest alpha versions of iam-client-lib and ew-did-registry
> feat(core): upgrate versions of iam-client-lib and ew-did-registry

- src/app/shared/services/login/login.service.ts
For this case i have e2e test. With the fix, test is passing.
> fix: issue when reinitializing session and user rejects metamask

- package-lock.json
- package.json
https://energyweb.atlassian.net/browse/IS-4
> bug/IS-4 can't request claim

- src/app/modules/connect-to-wallet/connect-buttons/connect-buttons.component.html
- src/app/modules/connect-to-wallet/connect-buttons/connect-buttons.component.scss
- src/app/modules/connect-to-wallet/connect-buttons/connect-buttons.component.spec.ts
- src/app/modules/connect-to-wallet/connect-buttons/connect-buttons.component.ts
- src/app/modules/connect-to-wallet/connect-to-wallet.module.ts
- src/app/modules/connect-to-wallet/ekc-settings/ekc-settings.component.html
- src/app/modules/connect-to-wallet/ekc-settings/ekc-settings.component.spec.ts
- src/app/modules/connect-to-wallet/ekc-settings/ekc-settings.component.ts
- src/app/modules/connect-to-wallet/ekc-settings/services/ekc-settings.service.spec.ts
- src/app/modules/connect-to-wallet/ekc-settings/services/ekc-settings.service.ts
- src/app/shared/services/env/env.service.ts
- src/app/shared/services/iam.service.spec.ts
- src/app/shared/services/iam.service.ts
- src/app/tests/mocks/dialog-data-mock.ts
- src/app/utils/validators/url/is-url.validator.spec.ts
- src/app/utils/validators/url/is-url.validator.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.stedin.ts
- src/environments/environment.stg.ts
- src/environments/environment.ts
service for ekc settings
component for setting ekc url.
add: validator for checking url
add: validation and setting predefined azure url settings.
> feat: implement ekc azure settings that can be modified by user at any time and stored in localstorage

- src/app/state/governance/organization/organization.effects.spec.ts
- src/app/state/governance/organization/organization.effects.ts
Fix for: https://energyweb.atlassian.net/browse/ICL-205
> fix: displaying not owner organizations

- package.json
Updating npm and node was done earlier. Now i just added information to package.json
> chore!: drop support for npm in version below 7

- package-lock.json
- package.json
- src/app/shared/services/env/env.service.ts
- src/app/shared/services/iam.service.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.stedin.ts
- src/environments/environment.stg.ts
- src/environments/environment.ts
> feat: update claim manager address

- src/app/modules/issue-vc/new-issue-vc/new-issue-vc.component.html
- src/app/modules/issue-vc/new-issue-vc/new-issue-vc.component.spec.ts
- src/app/modules/issue-vc/new-issue-vc/new-issue-vc.component.ts
- src/app/routes/assets/asset-list/asset-list.component.html
- src/app/routes/assets/asset-list/asset-list.component.ts
- src/app/routes/registration/role-precondition-list/role-precondition-list.component.ts
fix for: https://energyweb.atlassian.net/browse/IS-17
> fix: issue vc from assets view.

- .github/workflows/cf-deploy.yml
- package.json
Also cleans up deploy workflow.
> fix: builds for different envs

- src/app/shared/services/claims-facade/claims-facade.service.ts
Just for testing purposes to get info why it's failing here https://energyweb.atlassian.net/browse/SWTCH-1361. What is wrong with that object.
> chore: console logs to get errors from checking on chain revocation status

- src/app/state/auth/auth.effects.ts
- Temporarily remove call for revokable claims on init to see if JSON RPC errors stop
> fix: remove revokables call on init

- src/app/shared/services/claims-facade/claims-facade.service.spec.ts
- src/app/shared/services/claims-facade/claims-facade.service.ts
- src/app/state/auth/auth.effects.ts
- Fix for JSON RPC error when fetching enrollments
> Enrolment list bug

- src/app/routes/applications/new-role/components/validity-period/validity-period.component.spec.ts
- src/app/routes/applications/new-role/components/validity-period/validity-period.component.ts
- src/app/routes/enrolment/utils/format-validity-period-string.ts
- src/app/routes/enrolment/view-requests/components/expiration-date/expiration-date.component.html
- src/app/routes/enrolment/view-requests/components/expiration-date/expiration-date.component.spec.ts
- src/app/routes/enrolment/view-requests/components/expiration-date/expiration-date.component.ts
- src/app/routes/enrolment/view-requests/components/expiration-info/expiration-info.component.html
- src/app/routes/enrolment/view-requests/components/expiration-info/expiration-info.component.ts
- src/app/routes/enrolment/view-requests/issuer-requests/issuer-requests.component.html
- src/app/routes/enrolment/view-requests/issuer-requests/issuer-requests.component.ts
- src/app/shared/pipes/time-duration/timestamp.spec.ts
- src/app/shared/pipes/time-duration/timestamp.ts
https://energyweb.atlassian.net/browse/SWTCH-1380
> fix(exp): store defaultValidityPeriod as milliseconds

- src/app/routes/enrolment/revoke-enrolments/revoke-enrolment-list.component.html
- src/app/routes/enrolment/revoke-enrolments/revoke-enrolment-list.component.ts
> feat: display enrolment status on revocable list

- src/app/routes/applications/new-role/components/role-name/role-name.component.ts
- src/app/routes/applications/new-role/services/role-creation.service.spec.ts
- src/app/routes/applications/new-role/services/role-creation.service.ts
The tests were not updated and they were passing, but they shouldn't.
Tests are updated + fixed implementation. Now it show error message that domain already exist
> fix: creating role in domain that already exists

- src/app/routes/enrolment/services/revoke/revoke.service.ts
- src/app/shared/services/claims-facade/claims-facade.service.ts
- fix check to get into logic to check if a credential isRevoked
> fix(revocation): fix check for isRevoked logic

- src/app/routes/applications/actions/application-actions/application-actions.component.ts
- src/app/routes/applications/actions/role-actions/role-actions.component.spec.ts
- src/app/routes/applications/actions/role-actions/role-actions.component.ts
- src/app/routes/applications/new-role/components/role-name/role-name.component.spec.ts
- src/app/routes/applications/new-role/components/role-name/role-name.component.ts
- src/app/routes/applications/new-role/components/search-issuer-role/search-issuer-role.component.spec.ts
- src/app/routes/applications/new-role/components/search-issuer-role/search-issuer-role.component.ts
- src/app/routes/applications/new-role/new-role.component.spec.ts
- src/app/routes/applications/new-role/new-role.component.ts
- src/app/routes/applications/new-role/services/role-creation.service.spec.ts
- src/app/routes/applications/new-role/services/role-creation.service.ts
- src/app/state/governance/utils/filter-by/filter-by.ts
- src/app/utils/functions/domain-utils/domain-utils.spec.ts
- src/app/utils/functions/domain-utils/domain-utils.ts
- src/app/utils/functions/index.ts
Fixing again (😅) role name validation + small refactoring.
Issue was with wrong checked domain in method `isOwner`. And this lead me to create DomainUtils class for domain/namespace manipulation. I've changed only few places to reuse it.
> Fix role name async validation

- src/app/shared/services/env/env.service.ts
- src/app/shared/services/iam.service.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.stg.ts
- src/environments/environment.ts
- Sets Infura config values in .env files (maybe this should be in Github actions for privacy?)
- Instantiate connectToDidRegistry with Infura Auth
> fix(infura): instantiate did registry with infura config

- src/app/layout/header/dialog-user/dialog-user-data.ts
- src/app/layout/header/dialog-user/dialog-user.component.html
- src/app/layout/header/dialog-user/dialog-user.component.spec.ts
- src/app/layout/header/dialog-user/dialog-user.component.ts
- src/app/state/user-claim/user.reducer.ts
- src/app/state/user-claim/user.selectors.ts
fix for: https://energyweb.atlassian.net/browse/SWTCH-1394
Removes birthday and address fields.
Fix relies on id from DIDDocument (did). In localstorage we're storing all saved data from all accounts. It creates a connection DID <-> name.
> fix: issue with shared user data between accounts

- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.stedin.ts
- src/environments/environment.stg.ts
- src/environments/environment.ts
Infura project details rotated to new EW projects
> chore(config): rotating to EW SB Infura projects

- src/app/routes/search-result/search-result.component.html
- src/app/routes/search-result/search-result.component.spec.ts
- src/app/routes/search-result/search-result.component.ts
- Make call to get user requested claims. There was a placeholder there in the code to do so, but perhaps it was just forgotten. All variables were already in place, just no data fetched for them.
> fix: disable enrolment button if user already requested enrolment

- package-lock.json
- package.json
- src/app/routes/enrolment/view-requests/services/issuer-requests.service.spec.ts
- src/app/routes/enrolment/view-requests/services/issuer-requests.service.ts
- src/app/routes/search-result/search-result.component.html
- src/app/routes/search-result/search-result.component.spec.ts
- src/app/routes/search-result/search-result.component.ts
- src/environments/environment.prod.ts
Bug fixes, primary impetus to release is fix of prod ChainID
> merging develop to master

- src/app/routes/assets/asset-list/asset-list.component.html
> fix(assets): remove incorrect check for previously owned

- src/app/routes/assets/asset-enrolment-list/asset-enrolment-list.component.ts
https://energyweb.atlassian.net/jira/software/projects/SWTCH/boards/54?selectedIssue=SWTCH-1420
> fix: set enrolmentType #SWTCH-1420

- src/app/routes/enrolment/view-requests/issuer-requests/issuer-requests.component.html
- update notification string about signatures required for issuing claim
> fix: update signature advisory

- src/app/layout/header/header.component.html
- src/app/routes/dashboard/dashboard.component.html
- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/enrolment/enrolment.component.html
- src/app/routes/enrolment/enrolment.component.ts
- src/app/routes/enrolment/requested-enrolment-list/requested-enrolment-list.component.ts
- src/app/routes/registration/request-claim/request-claim.component.html
- src/app/routes/registration/request-claim/request-claim.component.ts
- src/app/routes/routes.ts
- src/app/state/enrolments/requested/requested.selectors.spec.ts
- src/app/state/enrolments/requested/requested.selectors.ts
- Remove experimental flag from all asset functionality
- https://www.loom.com/share/77b8fbba28c04c71b3ddc45b02e943cb
> fix: remove experimental flag for assets
