- src/app/routes/dashboard/dashboard.component.ts
Issue was that useMetamaskExtension param was removed so iam-client-lib was throwing exception when receiving receiving WalletProvider type that was not allowed.
Functionality may still not be ideal. Relogin on reload with metamask works. However, walletconnect/KM re-login likely does not. I don't believe it currently works on https://volta-switchboard.energyweb.org (master branch) either but I'm not certain. I'm not sure if the walletConnect library is checking for existing session information from local storage or if we would need to pass in an existing walletConnect session info into iam-client-lib and then re-establish the connection to the session based on that. Needs a bit more investigation on my part...
> fix(dashboard-init): restore re-login functionality

- src/app/routes/assets/asset-list/asset-list.component.ts
- src/app/routes/assets/edit-asset-dialog/edit-asset-dialog.component.ts
- src/app/routes/assets/operators/map-claims-profile.ts
Fixes 
1. problem when trying to register new asset and user didn't have user profile claim.
2. now should stop refreshing asset list when closing edit asset dialog component while not updating data.
3. now should stop closing edit asset dialog when clicking on backdrop.
> fix(SWTCH-942): assets for did without profile claim do not appear on the list.

- src/app/routes/assets/asset-list/asset-list.component.html
- src/app/routes/assets/verification-method/verification-method.component.html
- src/app/routes/assets/verification-method/verification-method.component.ts
- src/app/shared/directives/copyToClipboard/copy-to-clipboard.directive.ts
- src/app/shared/shared.module.ts
- src/app/utils/validators/is-hex.validator.spec.ts
- src/app/utils/validators/is-hex.validator.ts
Fixes to adding verification methods:
1. Added validation to accept Hex inputs as public key. Thanks to @JGiter for providing regex.
2. Change labels
3. Change toastr message to display Public key instead of Did.
4. Removed not needed css classes.
Additionaly added directive for copying to clipboard and displaying message with toastr - this can be used in multiple places where clipboard functionality is needed.
> [SWTCH-859] fixes to verification methods

- package-lock.json
- package.json
- src/app/routes/registration/request-claim/request-claim.component.ts
https://energyweb.atlassian.net/browse/SWTCH-982.
iam-cache-server is expecting a string for `selectedRole.version` and so casting to `string`.
I believe this is a regression introduced by https://energyweb.atlassian.net/browse/SWTCH-655 somewhere because `IRoleDefinition` now has `version` as a string. The ultimate solution is to migrate all of the legacy roles with their old string version to new integer version.
> bug(request-claim): cast role.version to string

- src/app/app.component.ts
- src/app/routes/assets/asset-enrolment-list/asset-enrolment-list.component.ts
- src/app/shared/services/url-service/url.service.ts
Previous solution wasn't working when navigating to asset enrolments from enrol/dashboard redirect. Back button was navigating to that page, but it was immediately redirecting to asset enrolments again. In that case back button will navigate to `asset` url which is my asset list.
> fix(SWTCH-990): not working back navigation when navigating from a url with redirect inside.

- src/app/routes/applications/new-application/new-application.component.html
- src/app/routes/applications/new-application/new-application.component.scss
- src/app/routes/applications/new-application/new-application.component.ts
- src/app/routes/applications/new-role/new-role.component.html
- src/app/routes/applications/new-role/new-role.component.scss
- src/app/routes/applications/new-role/new-role.component.ts
- src/app/utils/validators/is-alphanumeric.validator.spec.ts
- src/app/utils/validators/is-alphanumeric.validator.ts
Fixes for Role name (Role creation) and Application Namespace (Application creation).
For both:
1. Displays messege that field need to have at least 3 characters.
2. Field need to contain only alphanumeric values.
3. Can display multiple errors below a field - not like previously that field is required.
Fix only for Role name:
When Role name have incorrect value then user can't go further anymore.
> SWTCH-978 adjust role name field validation

- package-lock.json
- package.json
- src/app/routes/registration/request-claim/request-claim.component.html
- src/app/routes/registration/request-claim/request-claim.component.ts
- src/app/shared/styles/app/button-extra.scss
- src/app/utils/validators/require-checboxes-to-be-checked.validator.spec.ts
- src/app/utils/validators/require-checkboxes-to-be-checked.validator.ts
Displays checkboxes onChain/offChain <del>when user is enrolling for `Myself`</del> always - creates claim request with registrationTypes option.
This PR fixes also 2 bugs that i found while refactoring and testing this part of application.
1. There was invisible submit button when changing `Enrol for` into My Assets. Now it is visible and disabled.
2. sweetalert dialog wasn't disappearing when changing url. For example: try to enrol for a role that you already enroled. Next change roleName in url into something that you didn't enrol for. Dialog is visible but it shouldn't.
> SWTCH-958 implement UI request on chain credential

- src/app/app.module.ts
I don't know why it worked earlier for me locally. By removing `multi: true` application doesn't wait for array, it just takes an object. And object should be passed.
> SWTCH-1046 fix feature flag

- src/app/routes/assets/operators/retry-when-with-delay.ts
- src/app/routes/assets/verification-method/verification-method.component.ts
- src/app/routes/assets/verification-method/verification.service.spec.ts
- src/app/routes/assets/verification-method/verification.service.ts
Adds retry when updating verification methods list. It tries 5 times every 2 seconds. If list will be the same after retries it will display a message that backend doesn't have newest blockchain data.
In my tests I saw that max time difference was 3-4 seconds.
> SWTCH-1035 list of methods doesnt change

- src/app/routes/ewt-patron/patron-login.service.ts
- src/app/shared/services/iam.service.ts
only metamask connection is necessary for patron staking
No signature should be required
rename to `initDID` to match `iam-client-lib`
> fix(patron-login): initCacheServer&initDID = false

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.html
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.scss
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.spec.ts
- src/app/routes/ewt-patron/ewt-patron/ewt-patron.component.ts
- src/app/routes/ewt-patron/patron-login.service.ts
- src/app/routes/ewt-patron/stake/stake.component.html
- src/app/routes/ewt-patron/stake/stake.component.ts
- src/app/routes/routes.module.ts
- src/app/routes/routes.ts
- src/app/shared/services/iam.service.ts
- src/app/state/auth/auth.actions.ts
- src/app/state/auth/auth.effects.spec.ts
- src/app/state/auth/auth.effects.ts
- src/app/state/auth/auth.reducer.spec.ts
- src/app/state/auth/auth.reducer.ts
- src/app/state/auth/auth.selectors.spec.ts
- src/app/state/auth/auth.selectors.ts
- src/app/state/root.reducer.ts
- src/app/state/stake/stake.effects.spec.ts
- src/app/state/stake/stake.effects.ts
- src/app/state/stake/stake.reducer.spec.ts
- src/app/state/stake/stake.selectors.ts
- src/app/state/user-claim/user.effects.spec.ts
1. Changes login 
-> now user can login by clicking a button in top right corner to login
-> put value to stake and click stake button. After login it should try to putStake.
- if value is bigger than balance, then balance will be used instead.
- if user already put a stake to this provider, then nothing will be done. Just a message, that user already has put stake.
There is a workaround for handling stake after login. And there is no tests right now for it.
2. Removes lazy loaded module for staking, checking if this makes a problem with azure.
3. When user changes an account in metamask then he will no longer be redirected to main switchboard page. Now it should disconnect and reload a page.
4. Added error messages for stake amount input.
5. Refresh the page when user logout.
Things that …
> SWTCH-1111 change way of login for staking

- src/app/layout/header/header.component.html
When clicking on logo, page is reloaded and uses #. This fix will stop refreshing a page and removes # from url.
> fix switchboard header logo navigation.

- src/app/routes/enrolment/enrolment.component.ts
Problem occurs when trying to navigate from `enrolment requests` to `my enrolments` in `Enrolments` page. Previously it worked because we had loose equality. Now we have strict equality and we are comparing string to number.
> fix enrolment navigation.

- src/app/routes/applications/applications.component.html
- src/app/routes/applications/applications.component.ts
- src/app/state/organization/organization.selectors.ts
Button for creation sub organization was enabled always, even if we were looking on organization which namespace belongs to a different user.
> fix: SWTCH-1209 opening dialog for suborganization that do not belong to us

- src/app/shared/services/login/login.service.ts
The error occurs while trying to initialize iam, but error was thrown. Iam service is catching that error while calling `initializeConnection` method and do not rethrow that. With having that, there is no information for the user that something went wrong and user is able to click through application.
> fix: unhandled error while trying to initialize iam.

- package-lock.json
- package.json
There's a breaking rename of `chainName` to `chainDisplayName` that isn't yet handled.
> chg(deps): update iam-client-lib to 4.0.0-alpha.1

- .prettierignore
Renovate is failing when updating package-lock.json file, because prettier is checking that file. I think it is not needed to check that file as this is managed by npm.
> fix: renovate PRs with updates

- src/app/layout/components/user-menu/user-did/user-did.component.html
@Harasz mentioned that he see text in user menu near qr code. This should fix this issue.
> fix: displaying text near qr code icon

- src/app/routes/enrolment/models/enrolment-claim.spec.ts
- src/app/routes/enrolment/models/enrolment-claim.ts
- src/app/routes/enrolment/my-enrolment-list/my-enrolment-list.component.html
- src/app/routes/enrolment/my-enrolment-list/my-enrolment-list.component.ts
- Do not show Cancel Claim Request button in "My Enrolments" view IF the enrolment is revoked on-chain, or if it is revoked off-chain. 
For some reason, I can;t override the min-height on the mat-menu-panel, even if I put !important. I wish I could because it looks a little too tall when there is just one button...
> fix: Do not show Cancel Claim Request if claim is Revoked

- src/app/routes/enrolment/view-requests/components/expiration-date/expiration-date.component.spec.ts
- src/app/routes/enrolment/view-requests/components/expiration-date/expiration-date.component.ts
- src/app/routes/enrolment/view-requests/issuer-requests/issuer-requests.component.html
- src/app/routes/enrolment/view-requests/issuer-requests/issuer-requests.component.ts
- Was sending NaN to ICL as expirationTimestamp if date was removed. While this didn't affect ICL behavior as it is falsey, I think it should be changed to null in this case.
> fix(exp): do not send NaN as expiration date to ICL request

- src/app/routes/enrolment/view-requests/issuer-requests/issuer-requests.component.ts
- ICL is expecting undefined or number for expirationTimestamp. In keeping with the expected types, just changing this to undefined from 'null' if no value. 
- As one step further, we could not add expirationTimestamp to the request object to ICL if timestamp is undefined...
> fix(exp): use undefined vs null if no expirationTimestamp

- src/app/routes/applications/new-role/components/validity-period/validity-period.component.spec.ts
- src/app/routes/applications/new-role/components/validity-period/validity-period.component.ts
- src/app/routes/enrolment/view-requests/components/expiration-info/expiration-info.component.html
- src/app/shared/pipes/time-duration/time-duration.pipe.spec.ts
- src/app/shared/pipes/time-duration/time-duration.pipe.ts
- src/app/shared/pipes/time-duration/timestamp.ts
- src/app/shared/pipes/time-shift/time-shift.pipe.spec.ts
- src/app/shared/pipes/time-shift/time-shift.pipe.ts
This addresses https://energyweb.atlassian.net/jira/software/projects/SWTCH/boards/54?selectedIssue=SWTCH-1389
- The fundamental issue was the validity period component was relying on seconds after the validity period (after clicking "Next" on new role form) was converted to milliseconds. As a result, if you input a validity period, clicked "next" and then clicked "back", the input fields did not have the correct numbers. 
- As a fix, I have this component now accepting milliseconds. There is no instance in any of the validity or expiration components where seconds are being used now. Everything is now using milliseconds only. I think this makes things easier as we don't have to divide by 1000 anywhere etc. 
I will test this more.
> fix(exp): have validity period components accept miliseconds

- src/app/routes/enrolment/enrolment-list/filter-builder/filter.builder.ts
- src/app/routes/enrolment/enrolment-status/enrolment-status.component.html
- src/app/routes/enrolment/models/enrolment-claim.spec.ts
- src/app/routes/enrolment/models/enrolment-claim.ts
- create getter (canPublishClaim) to determine if "Publish" button should be shown for pending claims on My Enrolments tab
- Add unit tests for isExpired and canPublishClaim getter
> fix(exp): do not show 'Publish' button for expired claims

- src/app/core/config/chain-id.ts
- src/app/layout/layout.component.ts
- src/app/shared/services/login/helpers/login-swal.buttons.ts
- src/app/shared/services/login/login.service.spec.ts
- src/app/shared/services/login/login.service.ts
- src/app/shared/styles/app/for-theme.scss
- src/app/state/auth/auth.effects.spec.ts
- src/app/state/auth/auth.effects.ts
- src/app/state/auth/auth.selectors.spec.ts
- src/app/state/auth/auth.selectors.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.stedin.ts
- src/environments/environment.stg.ts
- src/environments/environment.ts
https://energyweb.atlassian.net/browse/SWTCH-1379
Fix works like this:
1. When app detects metamask with wrong chainId but will try to reinitialize with wrong chainId, then popup with logout button will be displayed.
2. When metamask is not present, then it's doing nothing.
3. when chain id is wrong, but it will not try to reinitialize with metamask (for example user was using mobile connect), then nothing is doing.
> fix: errors when reinitializing SB with wrong metamask network id

- package-lock.json
- package.json
- src/app/routes/enrolment/models/enrolment-claim.ts
- src/app/state/enrolments/owned/owned.selectors.spec.ts
- src/app/state/enrolments/owned/owned.selectors.ts
- src/app/state/enrolments/requested/requested.selectors.spec.ts
- src/app/state/enrolments/requested/requested.selectors.ts
- "For Approval" and "Publish" task counts were incorrect due to not taking into account revoked and expired credentials
- Numbers now match the Enrolments list
With updates:
Previously:
> fix: update logic for pending and to sync Task counts

- src/app/routes/dashboard/dashboard.component.spec.ts
- src/app/routes/dashboard/dashboard.component.ts
- src/app/routes/registration/request-claim/request-claim.component.ts
- src/app/routes/verifiable-presentation/verifiable-presentation/verifiable-presentation.component.ts
- src/app/shared/services/env/env.service.ts
- src/app/shared/services/iam.service.ts
- src/app/shared/services/login/login.service.spec.ts
- src/app/shared/services/login/login.service.ts
- src/app/state/auth/auth.actions.ts
- src/app/state/auth/auth.effects.spec.ts
- src/app/state/auth/auth.effects.ts
- src/app/state/auth/auth.reducer.ts
- src/app/state/auth/auth.selectors.spec.ts
- src/app/state/auth/auth.selectors.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.stedin.ts
- src/environments/environment.stg.ts
- src/environments/environment.ts
It fixes two issues:
https://energyweb.atlassian.net/browse/SWTCH-1399
https://energyweb.atlassian.net/browse/SWTCH-1397
The issue for 1399 was a race condition between getting Metamask details and reinitialization (reinitialization was first always). Now it tries to reinitialize user after getting metamask information. I've split reinitialization on two separate actions: one with metamask, second without.
Adds timer for reinitialization (1397) - 1 minute to reinitialize like while logging in. If user do nothing, it will display popup.
> Fix unable to complete login signature
